//Add non-agent stimuli picture filenames (240x360 px) and strings here
var stims = {
	stimDir: "",
	stimuli: ["filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",		
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",
		"filename1.jpg",	
	],
	prompts:[
		"Pitäisikö korkeakoulun järjestämän kurssin olla työntekijälle ilmaista?",
		"Pitäisikö koulutus- tai konsultointiyrityksen järjestämän kurssin olla työntekijälle ilmaista?",
		"Pitäisikö kurssi järjestää työpäivän aikana?",
		"Pitäisikö kurssi järjestää arki-iltaisin (työntekijän vapaa-aikana)?",
		"Pitäisikö kurssi järjestää viikonloppuisin (työntekijän vapaa-aikana)?",
		"Pitäisikö kurssi järjestää työntekijän kesäloman aikana?",
		"Pitäisikö tiettyjen kurssien olla pakollisia työntekijöille?",
		"Pitäisikö kurssien olla älyllisesti vaativia?",
		"Pitäisikö työntekijän osallistua korkeakoulun järjestämille kursseille säännöllisesti?",
		"Pitäisikö työntekijän osallistua koulutus- tai konsulttiyrityksen järjestämille kursseille säännöllisesti?",
		"Pitäisikö työnantajan maksaa koulutus- tai konsulttiyrityksen järjestämä maksullinen kurssi, johon työntekijä osallistuu?",
		"Pitäisikö työnantajan maksaa korkeakoulun järjestämä maksullinen kurssi, johon työntekijä osallistuu?",
		"Pitäisikö työnantajan palkita vapaa-ajallaan kursseille osallistuvia työntekijöitä?",
		"Pitäisikö kurssit järjestää etäällä työpaikasta esimerkiksi kongressikeskuksessa, jossa osallistujat yöpyvät?",
		"Pitäisikö kurssit järjestää työpaikalla?",
		"Pitäisikö täydennyskoulutus järjestää korkeakoulun tiloissa?",
		"Pitäisikö kurssien parantaa osallistujien henkistä hyvinvointia?",
		"Pitäisikö professorin opettaa kursseilla?",
		"Pitäisikö konsultin opettaa kursseilla?",
		"Pitäisikö ammattitaitoisen henkilön opettaa kursseilla?",
		"Pitäisikö kurssien parantaa työntekijöiden ammatillista osaamista?",
		"Pitäisikö kurssien parantaa työntekijöiden teoreettista ymmärrystä?",
		"Pitäisikö kurssien parantaa työntekijöiden yleissivistystä?",
		"Pitäisikö kurssien parantaa työntekijöiden fyysistä hyvinvointia?",
		"Pitäisikö kurssien parantaa työntekijän asemaa työmarkkinoilla?",
		"Pitäisikö kurssien tukea työntekijöiden harrastuksia?",
		"Pitäisikö kurssien edistää eri yritysten työntekijöiden välistä verkostoitumista?",
		"Pitäisikö kurssien lisätä työntekijöiden kykyä tarkastella työpaikan ongelmia useasta eri näkökulmasta?",
		"Pitäisikö kurssien kuluttaa mahdollisimman vähän työntekijöiden henkistä energiaa?",
		"Pitäisikö kurssien auttaa työntekijöiden kykyä huomioida työpaikan kollegoja?",
		"Pitäisikö kurssien olla työntekijöiden hyödynnettävissä osana korkeakoulututkintoa?",
		"Pitäisikö kurssien parantaa työntekijöiden motivaatiota työntekoon?",
		"Pitäisikö kursseilla käsitellä yhteiskuntaan laajasti liittyviä asioita työntekijän alan ulkopuolelta?",
		"Pitäisikö kurssien parantaa työntekijöiden kykyä soveltaa opittuja asioita tietoa työpaikan käytännön tilanteisiin?",
		"Pitäisikö kurssien parantaa työntekijöiden ihmissuhdetaitoja?",
		"Pitäisikö kurssien lisätä työntekijöiden luovuutta?",
		"Pitäisikö kurssien vahvistaa työntekijöiden myönteistä minäkäsitystä?",
		"Pitäisikö kurssien parantaa työntekijöiden digitaitoja?",
		"Pitäisikö kurssien parantaa työntekijöiden ryhmätyötaitoja?",
		"Pitäisikö kurssien parantaa työntekijöiden kykyä työskennellä tehokkaammin?",
		"Pitäisikö täydennyskoulutus järjestää verkko-opetuksena?",
		"Pitäisikö täydennyskoulutus järjestää kasvokkain?",
		"Pitäisikö täydennyskoulutus järjestää työpajoina, joissa työntekijät ratkovat tehtäviä yhdessä?",
		"Pitäisikö täydennyskoulutus järjestää luento-opetuksena?",
		"Pitäisikö täydennyskoulutus järjestää monimuoto-opetuksena (verkko-opetus ja kasvokkain opetus sekä luentoja ja työpajoja)?",
		"Pitäisikö täydennyskoulutuksen sisältää vaativia kotitehtäviä?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden valmiutta ottaa haltuun uudenlaisia työtehtäviä ja työtapoja?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden kykyä toimeenpanna uusia ideoita?",
	],
	main_questions_statement: [
		'Kurssi auttaa sinua etenemään työurallasi.',
		'Kurssi auttaa sinua soveltamaan tieteellistä tietoa työssäsi.', 
		'Kurssi auttaa sinua muuttamaan omaa ajatteluasi ja toimintaasi työelämässä.', 
		'Kurssi auttaa edustamaasi yritystä pärjäämään paremmin kilpailussa.',   
		'Kurssi auttaa edustamaasi yritystä muuttamaan nykyisiä käytäntöjä.', 
		'Kurssi auttaa ratkaisemaan paljon ajattelua edellyttäviä ongelmia edustamassasi yrityksessä.',
		],
	main_questions_question: [
    'Haluatko osallistua kurssille, joka auttaa sinua etenemään työurallasi?',
    'Haluatko osallistua kurssille, joka auttaa sinua soveltamaan tieteellistä tietoa työssäsi?',
    'Haluatko osallistua kurssille, joka auttaa sinua muuttamaan omaa ajatteluasi ja toimintaasi työelämässä?',
    'Haluatko osallistua kurssille, joka auttaa edustamaasi yritystä pärjäämään paremmin kilpailussa?',
    'Haluatko osallistua kurssille, joka auttaa edustamaasi yritystä muuttamaan nykyisiä käytäntöjä?',
    'Haluatko osallistua kurssille, joka auttaa ratkaisemaan paljon ajattelua edellyttäviä ongelmia edustamassasi yrityksessä?'],
};
