//Add non-agent stimuli picture filenames (240x360 px) and strings here
var stims = {
	stimDir: "",
	stimuli: [
		"filename1.jpg",
		"filename2.jpg",
		"filename3.jpg",
		"filename4.jpg",
		"filename5.jpg",
		"filename6.jpg",
		"filename7.jpg",
		"filename8.jpg",
		"filename9.jpg",
		"filename10.jpg",
		"filename11.jpg",
		"filename12.jpg",
		"filename13.jpg",
		"filename14.jpg",
		"filename15.jpg",
		"filename16.jpg",
		"filename17.jpg",
		"filename18.jpg",
		"filename19.jpg",
		"filename20.jpg",
		"filename21.jpg",
		"filename22.jpg",
		"filename23.jpg",
		"filename24.jpg",
		"filename25.jpg",
		"filename26.jpg",
		"filename27.jpg",
		"filename28.jpg",
		"filename29.jpg",
		"filename30.jpg",
		"filename31.jpg",
		"filename32.jpg",
		"filename33.jpg",
		"filename34.jpg",
		"filename35.jpg",
		"filename36.jpg",
		"filename37.jpg",
		"filename38.jpg",
		"filename39.jpg",
		"filename40.jpg",
		"filename41.jpg",
		"filename42.jpg",
		"filename43.jpg",
		"filename44.jpg",
		"filename45.jpg",
		"filename46.jpg",
		"filename47.jpg",
		"filename48.jpg"
		
	],
	prompts:[
		"Pitäisikö täydennyskoulutuksen olla maksutonta?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijän tietoa teknologiasta?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijän teknologista osaamista?",
		"Pitäisikö täydennyskoulutus järjestää työpäivän aikana?",
		"Pitäisikö täydennyskoulutus järjestää arki-iltaisin?",
		"Pitäisikö täydennyskoulutus järjestää viikonloppuisin?",
		"Pitäisikö täydennyskoulutus järjestää kesäloman aikana?",
		"Pitäisikö täydennyskoulutuksen olla älyllisesti vaativaa?",
		"Pitäisikö työntekijöiden osallistua täydennyskoulutukseen säännöllisesti?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden ymmärrystä ihmisen käyttäytymisestä?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden ymmärrystä taloudellisista asioista?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden ymmärrystä tuotteiden ja palveluiden muotoilusta?",
		"Pitäisikö työnantajan palkita vapaa-ajallaan täydennyskoulutukseen osallistuvia työntekijöitä?",
		"Pitäisikö täydennyskoulutus järjestää etäällä työpaikasta (esimerkiksi kongressikeskuksessa), jossa osallistujat yöpyvät? ",
		"Pitäisikö täydennyskoulutus järjestää työpaikalla?",
		"Pitäisikö täydennyskoulutus järjestää korkeakoulun tiloissa? ",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden esimies- ja johtamistaitoja?",
		"Pitäisikö professorin opettaa täydennyskoulutuskurssilla?",
		"Pitäisikö konsultin opettaa täydennyskoulutuskurssilla?",
		"Pitäisikö paljon ammatillista osaamista omaavan henkilön opettaa täydennyskoulutuskurssilla? ",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden ammatillista osaamista?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden teoreettista ymmärrystä?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden yleissivistystä?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden valmiutta kohdata digitalisaation aiheuttamat muutokset työpaikoilla?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden asemaa työmarkkinoilla?",
		"Pitäisikö täydennyskoulutuksen auttaa työntekijöitä soveltamaan tekoälyä työpaikoilla?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden verkostoitumista?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden kykyä tarkastella työpaikan ongelmia useasta eri näkökulmasta?",
		"Pitäisikö täydennyskouluksen lisätä työntekijöiden oma-aloitteisuutta työpaikalla?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden kykyä muodostaa omaan työntekoon liittyviä myönteisiä tulevaisuuden vaihtoehtoja. ",
		"Pitäisikö työntekijöiden voida hyödyntää täydennyskoulutussuoritukset osana tutkintoa?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden koulutusmyönteisyyttä?",
		"Pitäisikö täydennyskoulutuksessa käsitellä laajasti yhteiskuntaan liittyviä asioita työntekijöiden alan ulkopuolelta?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden kykyä soveltaa opittua tietoa työpaikan käytännön tilanteisiin?",
		"Pitäisikö samalle täydennyskoulutuskurssille osallistua työntekijöitä mahdollisimman monelta eri alalta?",
		"Pitäisikö täydennyskoulutuksen lisätä työntekijöiden luovuutta?",
		"Pitäisikö täydennyskoulutuksen vahvistaa työntekijöiden myönteistä minäkäsitystä?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden digitaitoja?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden ryhmätyötaitoja?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden kykyä työskennellä tehokkaammin?",
		"Pitäisikö täydennyskoulutus järjestää verkko-opetuksena?",
		"Pitäisikö täydennyskoulutus järjestää kasvokkain?",
		"Pitäisikö täydennyskoulutus järjestää työpajoina, joissa työntekijät ratkovat tehtäviä yhdessä?",
		"Pitäisikö täydennyskoulutus järjestää luento-opetuksena?",
		"Pitäisikö täydennyskoulutus järjestää monimuoto-opetuksena (verkko-opetus ja kasvokkain opetus sekä luentoja ja työpajoja)?",
		"Pitäisikö täydennyskoulutuksen sisältää vaativia kotitehtäviä?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden valmiutta ottaa haltuun uudenlaisia työtehtäviä ja työtapoja?",
		"Pitäisikö täydennyskoulutuksen parantaa työntekijöiden kykyä toimeenpanna uusia ideoita?",
	]
};
